- 0x0D40:
      - 0x20FF
      - 0x10
      - 0x0
      - 0x0
      - 0x0
      - 0x16
- 0x0C80:
      - 0x21
      - 0x22
      - 0x23
      - 0x24
      - 0x25
      - 0x26
      - 0x27
      - 0x28
- 0x0CC0:
      - 0x0
      - 0x0
      - 0x0
      - 0x0
      - 0x0
      - 0x0
      - 0x0
      - 0x0
      - 0x0
      - 0x0
      - 0x0
      - 0x0
- 0x0D60:
      - 0x7
      - 0x64
- 0x0D24C:
      - 0x51
      - 0x52
      - 0x53
      - 0x54
- 0x0AFC:
      - 0x11
      - 0x12
      - 0x20FF
      - 0x10
      - 0x0
      - 0x0
      - 0x0
      - 0x16
      - 0x21
      - 0x22
      - 0x23
      - 0x24
- 0x8D00:
      - 0x0