- 0x0D40:
    - 0xFF
    - 0x100
    - 0x0
    - 0x0
    - 0x1
    - 0x0
- 0x0C80:
    - 0x0
    - 0x152A
    - 0x203
    - 0x508
    - 0x4
    - 0x189
    - 0x7A2D
    - 0xA4
- 0x0CC0:
    - 0x190
    - 0x62A
    - 0x203
    - 0x508
    - 0xC
    - 0xE
    - 0x0
    - 0x0
    - 0x0
    - 0x0
    - 0x1A
    - 0xB4